<a href="https://colab.research.google.com/github/rakasadiantara/2021frontend/blob/main/%5BKlasifikasi%5D_Submission_Akhir_BMLP_I_Gede_Raka_Sadiantara.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Penting**
- Jangan mengubah atau menambahkan cell text yang sudah disediakan, Anda hanya perlu mengerjakan cell code yang sudah disediakan.
- Pastikan seluruh kriteria memiliki output yang sesuai, karena jika tidak ada output dianggap tidak selesai.
- Misal, Anda menggunakan df = df.dropna() silakan gunakan df.isnull().sum() sebagai tanda sudah berhasil. Silakan sesuaikan seluruh output dengan perintah yang sudah disediakan.
- Pastikan Anda melakukan Run All sebelum mengirimkan submission untuk memastikan seluruh cell berjalan dengan baik.
- Pastikan Anda menggunakan variabel df dari awal sampai akhir dan tidak diperbolehkan mengganti nama variabel tersebut.
- Hapus simbol pagar (#) pada kode yang bertipe komentar jika Anda menerapkan kriteria tambahan
- Biarkan simbol pagar (#) jika Anda tidak menerapkan kriteria tambahan
- Pastikan Anda mengerjakan sesuai section yang sudah diberikan tanpa mengubah judul atau header yang disediakan.

# **1. Import Library**
Pada tahap ini, Anda perlu mengimpor beberapa pustaka (library) Python yang dibutuhkan untuk analisis data dan pembangunan model machine learning.

In [ ]:
#Type your code here

import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split

from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, classification_report

from sklearn.model_selection import GridSearchCV

import joblib

import warnings
warnings.filterwarnings('ignore')

print("Semua library untuk tugas Klasifikasi telah berhasil diimport.")

Semua library untuk tugas Klasifikasi telah berhasil diimport.

# **2. Memuat Dataset dari Hasil Clustering**
Memuat dataset hasil clustering dari file CSV ke dalam variabel DataFrame.

In [ ]:
# Gunakan dataset hasil clustering yang memiliki fitur Target
# Silakan gunakan dataset data_clustering jika tidak menerapkan Interpretasi Hasil Clustering [Advanced]
# Silakan gunakan dataset data_clustering_inverse jika menerapkan Interpretasi Hasil Clustering [Advanced]
# Lengkapi kode berikut
# ___ = pd_read_csv("___.csv")

nama_file = 'data_clustering_inverse.csv'
df = pd.read_csv(nama_file)

print(f"Dataset '{nama_file}' berhasil dimuat.")

Dataset 'data_clustering_inverse.csv' berhasil dimuat.

In [ ]:
# Tampilkan 5 baris pertama dengan function head.

df.head()

,TransactionAmount,PreviousTransactionDate,TransactionType,Location,Channel,CustomerAge,CustomerOccupation,TransactionDuration,LoginAttempts,AccountBalance,TransactionDate,Target
0,14.09,2023-04-11 16:29:14,Debit,San Diego,ATM,70.0,Doctor,81.0,1.0,5112.21,2024-11-04 8:08:08,1
1,376.24,2023-06-27 16:44:19,Debit,Houston,ATM,68.0,Doctor,141.0,1.0,13758.91,2024-11-04 8:09:35,1
2,126.29,2023-07-10 18:16:08,Debit,Mesa,Online,19.0,Student,56.0,1.0,1122.35,2024-11-04 8:07:04,0
3,184.50,2023-05-05 16:32:11,Debit,Raleigh,Online,26.0,Student,25.0,1.0,8569.06,2024-11-04 8:09:06,1
4,92.15,2023-04-03 17:15:01,Debit,Oklahoma City,ATM,18.0,Student,172.0,1.0,781.68,2024-11-04 8:06:36,1

# **3. Data Splitting**
Tahap Data Splitting bertujuan untuk memisahkan dataset menjadi dua bagian: data latih (training set) dan data uji (test set).

In [ ]:
# Menggunakan train_test_split() untuk melakukan pembagian dataset.

y = df['Target']
X = df.drop(columns=['Target'])

date_cols = X.select_dtypes(include=['object']).filter(like='Date').columns
X = X.drop(columns=date_cols)
print(f"Kolom tanggal yang dihapus: {date_cols.tolist()}")

categorical_features_to_encode = X.select_dtypes(include=['object']).columns.tolist()
X = pd.get_dummies(X, columns=categorical_features_to_encode, drop_first=True)

print("\nFitur kategorikal telah di-handle. Berikut 5 baris pertama dari data fitur (X):")
display(X.head())
print("-" * 50)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

print("Proses Data Splitting Selesai.")
print(f"Bentuk X_train: {X_train.shape}")
print(f"Bentuk X_test: {X_test.shape}")

Kolom tanggal yang dihapus: ['PreviousTransactionDate', 'TransactionDate']

Fitur kategorikal telah di-handle. Berikut 5 baris pertama dari data fitur (X):

,TransactionAmount,CustomerAge,TransactionDuration,LoginAttempts,AccountBalance,TransactionType_Debit,Location_Atlanta,Location_Austin,Location_Baltimore,Location_Boston,...,Location_San Jose,Location_Seattle,Location_Tucson,Location_Virginia Beach,Location_Washington,Channel_Branch,Channel_Online,CustomerOccupation_Engineer,CustomerOccupation_Retired,CustomerOccupation_Student
0,14.09,70.0,81.0,1.0,5112.21,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,376.24,68.0,141.0,1.0,13758.91,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,126.29,19.0,56.0,1.0,1122.35,True,False,False,False,False,...,False,False,False,False,False,False,True,False,False,True
3,184.50,26.0,25.0,1.0,8569.06,True,False,False,False,False,...,False,False,False,False,False,False,True,False,False,True
4,92.15,18.0,172.0,1.0,781.68,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True

--------------------------------------------------
Proses Data Splitting Selesai.
Bentuk X_train: (1936, 53)
Bentuk X_test: (484, 53)

# **4. Membangun Model Klasifikasi**
Setelah memilih algoritma klasifikasi yang sesuai, langkah selanjutnya adalah melatih model menggunakan data latih.

Berikut adalah rekomendasi tahapannya.
1. Menggunakan algoritma klasifikasi yaitu Decision Tree.
2. Latih model menggunakan data yang sudah dipisah.

In [ ]:
# Buatlah model klasifikasi menggunakan Decision Tree

dt_model = DecisionTreeClassifier(random_state=42)

dt_model.fit(X_train, y_train)

print("Model Decision Tree berhasil dilatih.")

Model Decision Tree berhasil dilatih.

In [ ]:
# Menyimpan Model
# import joblib
# joblib.dump(model, 'decision_tree_model.h5')

joblib.dump(dt_model, 'decision_tree_model.h5')

print("Model berhasil disimpan sebagai 'decision_tree_model.h5'")

Model berhasil disimpan sebagai 'decision_tree_model.h5'

# **5. Memenuhi Kriteria Skilled dan Advanced dalam Membangun Model Klasifikasi**

**Biarkan kosong jika tidak menerapkan kriteria skilled atau advanced**

In [ ]:
# Melatih model menggunakan algoritma klasifikasi selain Decision Tree.

rf_model = RandomForestClassifier(random_state=42)
rf_model.fit(X_train, y_train)
print("Model Random Forest berhasil dilatih.")

lr_model = LogisticRegression(random_state=42, max_iter=1000)
lr_model.fit(X_train, y_train)
print("Model Logistic Regression berhasil dilatih.")

Model Random Forest berhasil dilatih.
Model Logistic Regression berhasil dilatih.

In [ ]:
# Menampilkan hasil evaluasi akurasi, presisi, recall, dan F1-Score pada seluruh algoritma yang sudah dibuat.

models = {
    "Decision Tree": dt_model,
    "Random Forest": rf_model,
    "Logistic Regression": lr_model
}

for name, model in models.items():
    y_pred = model.predict(X_test)
    print(f"--- Laporan Evaluasi untuk Model: {name} ---")
    print(classification_report(y_test, y_pred))
    print("="*55)

--- Laporan Evaluasi untuk Model: Decision Tree ---
              precision    recall  f1-score   support

           0       0.25      0.26      0.25       122
           1       0.29      0.30      0.29       121
           2       0.24      0.21      0.22       122
           3       0.30      0.30      0.30       119

    accuracy                           0.27       484
   macro avg       0.27      0.27      0.27       484
weighted avg       0.27      0.27      0.27       484

=======================================================
--- Laporan Evaluasi untuk Model: Random Forest ---
              precision    recall  f1-score   support

           0       0.27      0.30      0.29       122
           1       0.24      0.23      0.23       121
           2       0.27      0.27      0.27       122
           3       0.24      0.22      0.23       119

    accuracy                           0.26       484
   macro avg       0.26      0.26      0.26       484
weighted avg       0.26      0.26      0.26       484

=======================================================
--- Laporan Evaluasi untuk Model: Logistic Regression ---
              precision    recall  f1-score   support

           0       0.24      0.28      0.26       122
           1       0.25      0.21      0.23       121
           2       0.24      0.15      0.18       122
           3       0.28      0.39      0.33       119

    accuracy                           0.26       484
   macro avg       0.25      0.26      0.25       484
weighted avg       0.25      0.26      0.25       484

=======================================================

In [ ]:
# Menyimpan Model Selain Decision Tree
# Model ini bisa lebih dari satu
# import joblib
# joblib.dump(___, 'explore_<Nama Algoritma>_classification.h5')

import joblib

best_model_explore = rf_model

joblib.dump(best_model_explore, 'explore_RandomForest_classification.h5')

print("Model terbaik (Random Forest) berhasil disimpan sebagai 'explore_RandomForest_classification.h5'")

Model terbaik (Random Forest) berhasil disimpan sebagai 'explore_RandomForest_classification.h5'

Hyperparameter Tuning Model

Pilih salah satu algoritma yang ingin Anda tuning

In [ ]:
# Lakukan Hyperparameter Tuning dan Latih ulang.
# Lakukan dalam satu cell ini saja.

param_grid = {
    'n_estimators': [100, 200],
    'max_depth': [10, 20, None],
    'min_samples_leaf': [1, 2, 4]
}

grid_search = GridSearchCV(estimator=RandomForestClassifier(random_state=42),
                           param_grid=param_grid,
                           cv=3,
                           n_jobs=-1,
                           verbose=2,
                           scoring='f1_weighted')

grid_search.fit(X_train, y_train)

best_tuned_model = grid_search.best_estimator_

print("\nHyperparameter tuning selesai.")
print("Parameter terbaik yang ditemukan:", grid_search.best_params_)

Fitting 3 folds for each of 18 candidates, totalling 54 fits

Hyperparameter tuning selesai.
Parameter terbaik yang ditemukan: {'max_depth': 20, 'min_samples_leaf': 2, 'n_estimators': 200}

In [ ]:
# Menampilkan hasil evaluasi akurasi, presisi, recall, dan F1-Score pada algoritma yang sudah dituning.

y_pred_tuned = best_tuned_model.predict(X_test)

print("--- Laporan Evaluasi untuk Model Hasil Tuning ---")
print(classification_report(y_test, y_pred_tuned))

--- Laporan Evaluasi untuk Model Hasil Tuning ---
              precision    recall  f1-score   support

           0       0.22      0.23      0.22       122
           1       0.30      0.27      0.28       121
           2       0.28      0.32      0.30       122
           3       0.28      0.25      0.27       119

    accuracy                           0.27       484
   macro avg       0.27      0.27      0.27       484
weighted avg       0.27      0.27      0.27       484

In [ ]:
# Menyimpan Model hasil tuning
# import joblib
# joblib.dump(__, 'tuning_classification.h5')

joblib.dump(best_tuned_model, 'tuning_classification.h5')

print("Model hasil tuning berhasil disimpan sebagai 'tuning_classification.h5'")

Model hasil tuning berhasil disimpan sebagai 'tuning_classification.h5'

End of Code